/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc1155TokenReceiverSol from "./IERC1155TokenReceiver.sol";
export { IERC1155__factory } from "./IERC1155__factory";
