/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Attributes } from "./Attributes";
export type { IAttribute } from "./IAttribute";
export type { ITrait } from "./ITrait";
