/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiRolesAuthority__factory } from "./MultiRolesAuthority__factory";
export { RolesAuthority__factory } from "./RolesAuthority__factory";
