/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface AugmentsValidatorInterface extends utils.Interface {
  functions: {
    "addAugment(uint32,uint8,uint8,uint8)": FunctionFragment;
    "addOption(string,uint32)": FunctionFragment;
    "augmentExists(uint256)": FunctionFragment;
    "authority()": FunctionFragment;
    "character()": FunctionFragment;
    "convertToAugmentUUID(uint32,uint8,uint8,uint8)": FunctionFragment;
    "core()": FunctionFragment;
    "equipSkeleton(uint256,uint8)": FunctionFragment;
    "formToSlotCount(uint8)": FunctionFragment;
    "getAugmentIDByOption(string,uint8,uint8,uint8)": FunctionFragment;
    "getAugmentIDBySeries(uint32,uint8,uint8,uint8)": FunctionFragment;
    "optionStringToSeries(string)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeAugment(uint32,uint8,uint8,uint8)": FunctionFragment;
    "removeOption(string)": FunctionFragment;
    "setAuthority(address)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "slotCount()": FunctionFragment;
    "unequipSkeleton(uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAugment"
      | "addOption"
      | "augmentExists"
      | "authority"
      | "character"
      | "convertToAugmentUUID"
      | "core"
      | "equipSkeleton"
      | "formToSlotCount"
      | "getAugmentIDByOption"
      | "getAugmentIDBySeries"
      | "optionStringToSeries"
      | "owner"
      | "removeAugment"
      | "removeOption"
      | "setAuthority"
      | "setOwner"
      | "slotCount"
      | "unequipSkeleton"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAugment",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addOption",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "augmentExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(functionFragment: "character", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "convertToAugmentUUID",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "core", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "equipSkeleton",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "formToSlotCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAugmentIDByOption",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAugmentIDBySeries",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "optionStringToSeries",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAugment",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOption",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(functionFragment: "slotCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unequipSkeleton",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addAugment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addOption", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "augmentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "character", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertToAugmentUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "core", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "equipSkeleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formToSlotCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAugmentIDByOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAugmentIDBySeries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionStringToSeries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAugment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slotCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unequipSkeleton",
    data: BytesLike
  ): Result;

  events: {
    "AuthorityUpdated(address,address)": EventFragment;
    "OwnerUpdated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
}

export interface AuthorityUpdatedEventObject {
  user: string;
  newAuthority: string;
}
export type AuthorityUpdatedEvent = TypedEvent<
  [string, string],
  AuthorityUpdatedEventObject
>;

export type AuthorityUpdatedEventFilter =
  TypedEventFilter<AuthorityUpdatedEvent>;

export interface OwnerUpdatedEventObject {
  user: string;
  newOwner: string;
}
export type OwnerUpdatedEvent = TypedEvent<
  [string, string],
  OwnerUpdatedEventObject
>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface AugmentsValidator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AugmentsValidatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addOption(
      optionString: string,
      series: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    augmentExists(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    authority(overrides?: CallOverrides): Promise<[string]>;

    character(overrides?: CallOverrides): Promise<[string]>;

    convertToAugmentUUID(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    core(overrides?: CallOverrides): Promise<[string]>;

    equipSkeleton(
      id: BigNumberish,
      slotID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    formToSlotCount(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getAugmentIDByOption(
      option: string,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    getAugmentIDBySeries(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    optionStringToSeries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeOption(
      optionString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuthority(
      newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    slotCount(overrides?: CallOverrides): Promise<[number]>;

    unequipSkeleton(
      slotID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addAugment(
    series: BigNumberish,
    form: BigNumberish,
    rarity: BigNumberish,
    slot: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addOption(
    optionString: string,
    series: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  augmentExists(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  authority(overrides?: CallOverrides): Promise<string>;

  character(overrides?: CallOverrides): Promise<string>;

  convertToAugmentUUID(
    series: BigNumberish,
    form: BigNumberish,
    rarity: BigNumberish,
    slot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  core(overrides?: CallOverrides): Promise<string>;

  equipSkeleton(
    id: BigNumberish,
    slotID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  formToSlotCount(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  getAugmentIDByOption(
    option: string,
    form: BigNumberish,
    rarity: BigNumberish,
    slot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAugmentIDBySeries(
    series: BigNumberish,
    form: BigNumberish,
    rarity: BigNumberish,
    slot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  optionStringToSeries(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeAugment(
    series: BigNumberish,
    form: BigNumberish,
    rarity: BigNumberish,
    slot: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeOption(
    optionString: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuthority(
    newAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  slotCount(overrides?: CallOverrides): Promise<number>;

  unequipSkeleton(
    slotID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addOption(
      optionString: string,
      series: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    augmentExists(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    authority(overrides?: CallOverrides): Promise<string>;

    character(overrides?: CallOverrides): Promise<string>;

    convertToAugmentUUID(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    core(overrides?: CallOverrides): Promise<string>;

    equipSkeleton(
      id: BigNumberish,
      slotID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    formToSlotCount(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    getAugmentIDByOption(
      option: string,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAugmentIDBySeries(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optionStringToSeries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    removeOption(
      optionString: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthority(
      newAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(newOwner: string, overrides?: CallOverrides): Promise<void>;

    slotCount(overrides?: CallOverrides): Promise<number>;

    unequipSkeleton(
      slotID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AuthorityUpdated(address,address)"(
      user?: string | null,
      newAuthority?: string | null
    ): AuthorityUpdatedEventFilter;
    AuthorityUpdated(
      user?: string | null,
      newAuthority?: string | null
    ): AuthorityUpdatedEventFilter;

    "OwnerUpdated(address,address)"(
      user?: string | null,
      newOwner?: string | null
    ): OwnerUpdatedEventFilter;
    OwnerUpdated(
      user?: string | null,
      newOwner?: string | null
    ): OwnerUpdatedEventFilter;
  };

  estimateGas: {
    addAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addOption(
      optionString: string,
      series: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    augmentExists(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authority(overrides?: CallOverrides): Promise<BigNumber>;

    character(overrides?: CallOverrides): Promise<BigNumber>;

    convertToAugmentUUID(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    core(overrides?: CallOverrides): Promise<BigNumber>;

    equipSkeleton(
      id: BigNumberish,
      slotID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    formToSlotCount(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAugmentIDByOption(
      option: string,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAugmentIDBySeries(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optionStringToSeries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeOption(
      optionString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuthority(
      newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    slotCount(overrides?: CallOverrides): Promise<BigNumber>;

    unequipSkeleton(
      slotID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addOption(
      optionString: string,
      series: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    augmentExists(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    character(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    convertToAugmentUUID(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    core(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    equipSkeleton(
      id: BigNumberish,
      slotID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    formToSlotCount(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAugmentIDByOption(
      option: string,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAugmentIDBySeries(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    optionStringToSeries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeAugment(
      series: BigNumberish,
      form: BigNumberish,
      rarity: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeOption(
      optionString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuthority(
      newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    slotCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unequipSkeleton(
      slotID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
