/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomnessRelayL1Sol from "./RandomnessRelayL1.sol";
export type { randomnessRelayL1Sol };
export type { RandomnessRelayL2 } from "./RandomnessRelayL2";
