/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as selectableOptionsSol from "./SelectableOptions.sol";
export type { selectableOptionsSol };
import type * as attributes from "./attributes";
export type { attributes };
export type { Characters } from "./Characters";
