/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IEXPInterface extends utils.Interface {
  functions: {
    "getLVL(uint256)": FunctionFragment;
    "getXP(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getLVL" | "getXP"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLVL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getXP", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "getLVL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getXP", data: BytesLike): Result;

  events: {};
}

export interface IEXP extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEXPInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLVL(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getXP(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getLVL(
    characterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getXP(
    characterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getLVL(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getXP(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getLVL(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getXP(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLVL(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getXP(
      characterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
