/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReadMetadata,
  IReadMetadataInterface,
} from "../../../contracts/MetadataRegistry.sol/IReadMetadata";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "string",
        name: "metadata",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IReadMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IReadMetadataInterface {
    return new utils.Interface(_abi) as IReadMetadataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReadMetadata {
    return new Contract(address, _abi, signerOrProvider) as IReadMetadata;
  }
}
