/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as randomnessRelayL1Sol from "./RandomnessRelayL1.sol";
export { RandomnessRelayL2__factory } from "./RandomnessRelayL2__factory";
