/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as authSol from "./Auth.sol";
export type { authSol };
import type * as authorities from "./authorities";
export type { authorities };
