/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1155TokenReceiverSol from "./IERC1155TokenReceiver.sol";
export type { ierc1155TokenReceiverSol };
export type { IERC1155 } from "./IERC1155";
