/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VRFConsumerLite,
  VRFConsumerLiteInterface,
} from "../../../contracts/chainlink/VRFConsumerLite";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint32[]",
        name: "randomWords",
        type: "uint32[]",
      },
    ],
    name: "fulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VRFConsumerLite__factory {
  static readonly abi = _abi;
  static createInterface(): VRFConsumerLiteInterface {
    return new utils.Interface(_abi) as VRFConsumerLiteInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VRFConsumerLite {
    return new Contract(address, _abi, signerOrProvider) as VRFConsumerLite;
  }
}
