/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VRFRequesterL1,
  VRFRequesterL1Interface,
} from "../../../contracts/chainlink/VRFRequesterL1";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "requestRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VRFRequesterL1__factory {
  static readonly abi = _abi;
  static createInterface(): VRFRequesterL1Interface {
    return new utils.Interface(_abi) as VRFRequesterL1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VRFRequesterL1 {
    return new Contract(address, _abi, signerOrProvider) as VRFRequesterL1;
  }
}
