/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAchievement,
  IAchievementInterface,
} from "../../../contracts/interfaces/IAchievement";

const _abi = [
  {
    inputs: [],
    name: "getAchievement",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "characterId",
        type: "uint256",
      },
    ],
    name: "hasAchievement",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "characterId",
        type: "uint256",
      },
    ],
    name: "unlockAchievement",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

export class IAchievement__factory {
  static readonly abi = _abi;
  static createInterface(): IAchievementInterface {
    return new utils.Interface(_abi) as IAchievementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAchievement {
    return new Contract(address, _abi, signerOrProvider) as IAchievement;
  }
}
