/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFabricator721,
  IFabricator721Interface,
} from "../../../contracts/interfaces/IFabricator721";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectibleId",
        type: "uint256",
      },
    ],
    name: "idToValidator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "modularMintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_dropId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "_validator",
        type: "address",
      },
      {
        internalType: "string",
        name: "_metadata",
        type: "string",
      },
    ],
    name: "modularMintInit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectibleId",
        type: "uint256",
      },
    ],
    name: "quantityMinted",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFabricator721__factory {
  static readonly abi = _abi;
  static createInterface(): IFabricator721Interface {
    return new utils.Interface(_abi) as IFabricator721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFabricator721 {
    return new Contract(address, _abi, signerOrProvider) as IFabricator721;
  }
}
