/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMintValidator721,
  IMintValidator721Interface,
} from "../../../contracts/interfaces/IMintValidator721";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_dropId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_metadata",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "validate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMintValidator721__factory {
  static readonly abi = _abi;
  static createInterface(): IMintValidator721Interface {
    return new utils.Interface(_abi) as IMintValidator721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMintValidator721 {
    return new Contract(address, _abi, signerOrProvider) as IMintValidator721;
  }
}
