/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IREP, IREPInterface } from "../../../contracts/interfaces/IREP";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "characterId",
        type: "uint256",
      },
    ],
    name: "getREP",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "characterId",
        type: "uint256",
      },
    ],
    name: "getRNK",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IREP__factory {
  static readonly abi = _abi;
  static createInterface(): IREPInterface {
    return new utils.Interface(_abi) as IREPInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IREP {
    return new Contract(address, _abi, signerOrProvider) as IREP;
  }
}
