/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWearables,
  IWearablesInterface,
} from "../../../contracts/interfaces/IWearables";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "form",
        type: "uint8",
      },
    ],
    name: "formToSlotCount",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "option",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "form",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "slot",
        type: "uint8",
      },
    ],
    name: "getWearableIDByOption",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "series",
        type: "uint32",
      },
      {
        internalType: "uint8",
        name: "form",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "slot",
        type: "uint8",
      },
    ],
    name: "getWearableIDBySeries",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "option",
        type: "string",
      },
    ],
    name: "optionStringToSeries",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWearables__factory {
  static readonly abi = _abi;
  static createInterface(): IWearablesInterface {
    return new utils.Interface(_abi) as IWearablesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWearables {
    return new Contract(address, _abi, signerOrProvider) as IWearables;
  }
}
